version: '3'
services:
  app:
    container_name: golang_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
      - DATABASE_HOST=-db
      - DATABASE_PORT=54322
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    networks:
      - learning
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - TZ=Asia/Shanghai    
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - learning

# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge
volumes:
  db: